#!/bin/bash

function fetch_chemicals() {
  cd data
  curl -s -L -o chemicals-01-2016.csv \
    http://datagov.ic.nhs.uk/presentation/2016_01_January/T201601CHEM+SUBS.CSV
  curl -s -L -o chemicals-02-2016.csv \
    http://datagov.ic.nhs.uk/presentation/2016_02_February/T201602CHEM+SUBS.CSV

  echo "Dowloaded chemicals csv files."
  echo "Concatenating chemicals files."

  cp chemicals-01-2016.csv chemicals.csv
  tail -n+2 chemicals-02-2016.csv >> chemicals.csv

  echo "Concatenated chemicals files."

  rm -rf chemicals-{01,02}-2016.csv
  cd ..
}

function fetch_practices() {
  cd data
  curl -s -L -o practices-01-2016.csv \
    http://datagov.ic.nhs.uk/presentation/2016_01_January/T201601ADDR+BNFT.CSV
  curl -s -L -o practices-02-2016.csv \
    http://datagov.ic.nhs.uk/presentation/2016_02_February/T201602ADDR+BNFT.CSV

  echo "Dowloaded practices csv files."
  echo "Concatenating practices files."

  cp practices-01-2016.csv practices.csv
  cat practices-02-2016.csv >> practices.csv

  echo "Concatenated prescriptions files."

  rm -rf practices-{01,02}-2016.csv
  cd ..
}

function fetch_prescriptions() {
  cd data
  curl -s -L -o prescriptions-01-2016.csv \
    http://datagov.ic.nhs.uk/presentation/2016_01_January/T201601PDPI+BNFT.CSV
  curl -s -L -o prescriptions-02-2016.csv \
    http://datagov.ic.nhs.uk/presentation/2016_02_February/T201602PDPI+BNFT.CSV

  echo "Dowloaded prescriptions csv files."
  echo "Concatenating prescriptions files."

  cp prescriptions-01-2016.csv prescriptions.csv
  tail -n+2 prescriptions-02-2016.csv >> prescriptions.csv

  echo "Concatenated prescriptions files."
  echo "Adding index column to prescriptions."

  rm -rf prescriptions-{01,02}-2016.csv

  awk -v OFS=',' '
    NR == 1 {print "ID", $0; next}
    {print (NR-1), $0}
  ' prescriptions.csv > tmp && mv tmp prescriptions.csv

  "Done fetching prescriptions."

  cd ..
}

function fetch_gppatients() {
  cd data
  curl -s -L -o gppatients.csv \
    http://www.hscic.gov.uk/catalogue/PUB19775/gp-reg-patients-prac-quin-age.csv
  cd ..
}

checksum_chemicals=1b898694c32b96ecd74d85c201cc178e
checksum_practices=3a57b4a1b45a75fdd1eea19676c65691
checksum_prescriptions=bcf3aa7e0a53b5ff11f41e0e6e51dca5
checksum_gppatients=bba2a3aaa86d727dc53beff60007347a

FILES="
chemicals
practices
prescriptions
gppatients
"

mkdir -p data

for f in $FILES
do
  if [ ! -f "data/$f.csv" ]
  then
    echo ""
    echo "data/$f.csv - NOT FOUND. Downloading."
    echo "Depending on the size of the file(s) this might take a while."
    eval "fetch_$f"
  else
    file_checksum=$(md5 -q data/$f.csv)
    checksum_name="checksum_$f"
    correct_checksum=${!checksum_name}

    if [ $file_checksum == $correct_checksum ]
    then
      echo ""
      echo "data/$f.csv checksum - OK. Skipping download."
    else
      echo ""
      echo "data/$f.csv checksum - NOT OK. Re-downloading."
      echo "Depending on the size of the file(s) this might take a while."
      eval "fetch_$f"
    fi
  fi
done

cat src/sql/0{0-setup,1-views}.sql | mysql -u root -p
